#!/usr/bin/env python3
"""Generate PixlText's static Unicode NFC lookup tables."""

from pathlib import Path
import sys
import unicodedata


UNICODE_VERSION = "16.0.0"


def swift_hex(value: int) -> str:
    return f"0x{value:X}"


def wrapped(values: list[str], indent: str = "        ", width: int = 100) -> str:
    lines: list[str] = []
    line = indent
    for value in values:
        item = value + ","
        if len(line) + len(item) + 1 > width:
            lines.append(line.rstrip())
            line = indent
        line += item + " "
    if line.strip():
        lines.append(line.rstrip())
    return "\n".join(lines)


def main() -> None:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise RuntimeError(
            f"Expected Unicode {UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )
    if len(sys.argv) != 2:
        raise SystemExit("usage: GenerateUnicodeNormalization.py OUTPUT")

    decompositions: list[tuple[int, list[int]]] = []
    combining_classes: list[tuple[int, int]] = []
    compositions: list[tuple[int, int, int]] = []

    for scalar in range(0x110000):
        character = chr(scalar)
        combining_class = unicodedata.combining(character)
        if combining_class:
            combining_classes.append((scalar, combining_class))

        raw = unicodedata.decomposition(character)
        if not raw or raw.startswith("<") or 0xAC00 <= scalar <= 0xD7A3:
            continue
        mapping = [int(part, 16) for part in raw.split()]
        decompositions.append((scalar, mapping))
        if len(mapping) == 2 and unicodedata.normalize("NFC", "".join(map(chr, mapping))) == character:
            compositions.append((mapping[0], mapping[1], scalar))

    compositions.sort()

    decomposition_scalars: list[int] = []
    decomposition_entries: list[tuple[int, int, int]] = []
    for scalar, mapping in decompositions:
        decomposition_entries.append((scalar, len(decomposition_scalars), len(mapping)))
        decomposition_scalars.extend(mapping)

    source = f'''// Generated by Tools/GenerateUnicodeNormalization.py.
// Unicode {UNICODE_VERSION}. Do not edit by hand.

extension UnicodeNormalization {{
    static let unicodeVersion = "{UNICODE_VERSION}"

    struct DecompositionEntry {{
        let scalar: UInt32
        let offset: UInt16
        let count: UInt8
    }}

    struct CombiningClassEntry {{
        let scalar: UInt32
        let value: UInt8
    }}

    struct CompositionEntry {{
        let first: UInt32
        let second: UInt32
        let result: UInt32
    }}

    static let decompositionEntries: [DecompositionEntry] = [
{wrapped([f'.init(scalar: {swift_hex(s)}, offset: {o}, count: {c})' for s, o, c in decomposition_entries])}
    ]

    static let decompositionScalars: [UInt32] = [
{wrapped([swift_hex(s) for s in decomposition_scalars])}
    ]

    static let combiningClassEntries: [CombiningClassEntry] = [
{wrapped([f'.init(scalar: {swift_hex(s)}, value: {c})' for s, c in combining_classes])}
    ]

    static let compositionEntries: [CompositionEntry] = [
{wrapped([f'.init(first: {swift_hex(a)}, second: {swift_hex(b)}, result: {swift_hex(r)})' for a, b, r in compositions])}
    ]
}}
'''
    Path(sys.argv[1]).write_text(source)


if __name__ == "__main__":
    main()
