#!/usr/bin/env python3
"""Generate compact Unicode 16 properties used by UAX #14."""

from pathlib import Path
import sys


UNICODE_VERSION = "16.0.0"
CLASS_NAMES = [
    "AI", "AK", "AL", "AP", "AS", "B2", "BA", "BB", "BK", "CB", "CJ", "CL",
    "CM", "CP", "CR", "EB", "EM", "EX", "GL", "H2", "H3", "HL", "HY", "ID",
    "IN", "IS", "JL", "JT", "JV", "LF", "NL", "NS", "NU", "OP", "PO", "PR",
    "QU", "RI", "SA", "SG", "SP", "SY", "VF", "VI", "WJ", "XX", "ZW", "ZWJ",
]


def ranges(path: Path):
    for raw_line in path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        codepoints, value = [field.strip() for field in line.split(";")]
        if ".." in codepoints:
            lower, upper = (int(item, 16) for item in codepoints.split(".."))
        else:
            lower = upper = int(codepoints, 16)
        yield lower, upper, value


def assign(values, lower, upper, transform):
    for codepoint in range(lower, upper + 1):
        values[codepoint] = transform(values[codepoint])


def format_array(values, width=12):
    lines = []
    for index in range(0, len(values), width):
        lines.append("        " + ", ".join(str(value) for value in values[index:index + width]) + ",")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 6:
        raise SystemExit(
            "usage: GenerateUnicodeLineBreaks.py LineBreak.txt UnicodeData.txt "
            "EastAsianWidth.txt emoji-data.txt OUTPUT"
        )
    line_break_path, unicode_data_path, width_path, emoji_path, output_path = map(Path, sys.argv[1:])
    class_index = {name: index for index, name in enumerate(CLASS_NAMES)}
    values = [class_index["XX"]] * 0x110000

    for lower, upper, name in [
        (0x3400, 0x4DBF, "ID"), (0x4E00, 0x9FFF, "ID"), (0xF900, 0xFAFF, "ID"),
        (0x1F000, 0x1FAFF, "ID"), (0x1FC00, 0x1FFFD, "ID"),
        (0x20000, 0x2FFFD, "ID"), (0x30000, 0x3FFFD, "ID"),
        (0x20A0, 0x20CF, "PR"),
    ]:
        assign(values, lower, upper, lambda _: class_index[name])
    for lower, upper, name in ranges(line_break_path):
        assign(values, lower, upper, lambda _: class_index[name])

    categories = [None] * 0x110000
    pending = None
    for raw_line in unicode_data_path.read_text().splitlines():
        fields = raw_line.split(";")
        codepoint = int(fields[0], 16)
        name, category = fields[1], fields[2]
        if name.endswith(", First>"):
            pending = (codepoint, category)
        elif name.endswith(", Last>"):
            lower, pending_category = pending
            categories[lower:codepoint + 1] = [pending_category] * (codepoint - lower + 1)
            pending = None
        else:
            categories[codepoint] = category

    for codepoint, category in enumerate(categories):
        flags = 0
        if category == "Pi": flags |= 1 << 7
        if category == "Pf": flags |= 1 << 8
        if category in ("Mn", "Mc"): flags |= 1 << 9
        values[codepoint] |= flags

    for lower, upper, width in ranges(width_path):
        if width in ("F", "W", "H"):
            assign(values, lower, upper, lambda value: value | (1 << 6))
    for lower, upper, name in ranges(emoji_path):
        if name == "Extended_Pictographic":
            assign(values, lower, upper, lambda value: value | (1 << 10))

    page_starts = [0]
    entries = []
    for page in range(0x1100):
        page_values = values[page << 8:(page + 1) << 8]
        current = page_values[0]
        for offset in range(1, 256):
            if page_values[offset] != current:
                entries.append((offset - 1) | (current << 8))
                current = page_values[offset]
        entries.append(255 | (current << 8))
        page_starts.append(len(entries))

    if len(entries) > 0xFFFF:
        raise ValueError("page index no longer fits UInt16")
    Path(output_path).write_text(f'''// Generated by Tools/GenerateUnicodeLineBreaks.py.
// Unicode {UNICODE_VERSION}. Do not edit by hand.

extension UnicodeLineBreakProperty {{
    static let unicodeVersion = "{UNICODE_VERSION}"

    static let pageStarts: [UInt16] = [
{format_array(page_starts)}
    ]

    static let entries: [UInt32] = [
{format_array(entries)}
    ]
}}
''')


if __name__ == "__main__":
    main()
