#!/usr/bin/env python3
"""Generate PixlText's static Unicode Script-property ranges."""

from pathlib import Path
import sys


UNICODE_VERSION = "16.0.0"


def tag_value(tag: str) -> int:
    raw = tag.lower().encode("ascii")
    if len(raw) != 4:
        raise ValueError(tag)
    return int.from_bytes(raw, "big")


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("usage: GenerateUnicodeScripts.py Scripts.txt PropertyValueAliases.txt OUTPUT")

    scripts_path, aliases_path, output_path = map(Path, sys.argv[1:])
    aliases: dict[str, str] = {}
    for raw_line in aliases_path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(";")]
        if fields[0] == "sc":
            aliases[fields[2]] = fields[1]

    ranges: list[tuple[int, int, int]] = []
    for raw_line in scripts_path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        codepoints, name = [field.strip() for field in line.split(";")]
        if ".." in codepoints:
            lower, upper = (int(value, 16) for value in codepoints.split(".."))
        else:
            lower = upper = int(codepoints, 16)
        ranges.append((lower, upper, tag_value(aliases[name])))

    ranges.sort(key=lambda entry: entry[0])

    entries = "\n".join(
        f"        .init(lower: 0x{lower:X}, upper: 0x{upper:X}, tag: 0x{tag:X}),"
        for lower, upper, tag in ranges
    )
    output_path.write_text(f'''// Generated by Tools/GenerateUnicodeScripts.py.
// Unicode {UNICODE_VERSION}. Do not edit by hand.

extension UnicodeScript {{
    static let unicodeVersion = "{UNICODE_VERSION}"

    static let ranges: [RangeEntry] = [
{entries}
    ]
}}
''')


if __name__ == "__main__":
    main()
